// Generated by IcedCoffeeScript 1.3.3a
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    var Todo;
    return Todo = (function(_super) {

      __extends(Todo, _super);

      function Todo() {
        return Todo.__super__.constructor.apply(this, arguments);
      }

      defaults(function() {
        return {
          content: 'empty todo...',
          order: Todos.nextOrder(),
          done: false
        };
      });

      initialize(function() {
        if (!this.get('content')) {
          return this.set({
            'content': this.defaults.content
          });
        }
      });

      return Todo;

    })(Backbone.Model);
  });

}).call(this);
